### ISSUE TITLE
Not receiving any alerts on mail and telegram

### ISSUE THREAD

**Issue by ParagLawate** [J4FSec/In0ri#12]
After successfully running the app and setting up the SMTP setup , adding website URL to be monitored, I am not receiving any email alerts. After entering a valid Telegram chat id and bot token , it gives "Invalid token or chat id".
Another issue "url not captured" 
![image](https://github.com/J4FSec/In0ri/assets/113654241/c66c48f9-9dda-4f9b-a1a4-d02034059209)
![image](https://github.com/J4FSec/In0ri/assets/113654241/5d5a0919-71c9-4d35-a7bc-8412dd5f76be)

**Comment by FormindMPO** [comment]
Hey @ParagLawate, how did you solved `Token or Chat ID invalid` ?
Thank you !

**Comment by ParagLawate** [comment]
> Hey @ParagLawate, how did you solved `Token or Chat ID invalid` ? Thank you !

I couldn't solved it and didn't received any help from the repo owners.

**Comment by FormindMPO** [comment]
It appears that telegram updated their library and you now have to await results, this is why this original repo is not working :

```python
import asyncio
import telegram


async def main():
    bot = telegram.Bot("TOKEN")
    async with bot:
        print(await bot.get_me())


if __name__ == '__main__':
    asyncio.run(main())
```
(see https://github.com/python-telegram-bot/python-telegram-bot/wiki/Introduction-to-the-API)

I rewrote some of this stuff to fix it and may push a pull request to update this repo later
